### ISSUE TITLE
correct way to go about nested partials from separate files

### ISSUE THREAD

**Issue by sachaw** [zordius/HandlebarsCookbook#2]
I cannot seem to find where it says the appropriate way to do this,
say I have the file `\templates\dashboard.tmpl`
and within that I want to output the contents of `\templates\partials\header.tmpl`

**Comment by zordius** [comment]
You need to load partial files first, then tell handlebars engine all partials as `{ name: content, ... }` pairs.

**Comment by sachaw** [comment]
ok, thanks.
